#!/usr/bin/env bash
set -eu

echo "=== EasyFile Install ==="

# Generate .env if it doesn't exist
if [ ! -f .env ]; then
  SECRET=$(mix phx.gen.secret 2>/dev/null || echo "dev-secret-$(date +%s)-$(head -c 32 /dev/urandom | base64 | tr -d '/+=')")
  cat > .env <<EOF
# Generated by install.sh — change these for production
SECRET_KEY_BASE=${SECRET}
# PORT=4000
# PHX_HOST=example.com
# PHX_SERVER=true
EOF
  echo "Generated .env with random SECRET_KEY_BASE"
fi

# Install Hex and Rebar non-interactively
mix local.hex --force
mix local.rebar --force

# Fetch and compile dependencies
echo "--- Installing dependencies ---"
mix deps.get
mix deps.compile

# Set up the database (create, migrate, seed)
echo "--- Setting up database ---"
mix ecto.create 2>/dev/null || true
mix ecto.migrate
mix run priv/repo/seeds.exs

# Compile the application
echo "--- Compiling application ---"
mix compile

echo ""
echo "=== Setup complete ==="
echo "Run the server with: mix phx.server"
echo "Demo login: cenius@cenius.ai / cenius"
